import type { Metadata } from "next";
import { Geist, Geist_Mono, Zen_Old_Mincho } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import MobileMenu from "@/components/MobileMenu";
import Footer from "@/components/Footer";
import ReactLenis, { useLenis } from "lenis/react";
import IntroOverlay from "@/components/IntroOverlay";
import { MediaLoadingProvider } from "@/context/MediaLoadingContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const zenOldMincho = Zen_Old_Mincho({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MediaLoadingProvider>
        <ReactLenis root>
          <body className={`${zenOldMincho.className} antialiased`}>
            <IntroOverlay />
            <div
              className="fixed top-0 left-0 z-[999] h-screen w-screen"
              style={{
                backgroundImage: "url('/grainy-effect.webp')",
                mixBlendMode: "hard-light",
                opacity: 0.06,
                pointerEvents: "none",
              }}
            ></div>
            <div className="relative z-[90]">
              <Header />
              <MobileMenu />
              {children}
            </div>
            <Footer />
          </body>
        </ReactLenis>
      </MediaLoadingProvider>
    </html>
  );
}
