import type { Metadata } from "next";
import { Averia_Libre, DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ReactLenis from "lenis/react";
import IntroOverlay from "@/components/IntroOverlay";
import { MediaLoadingProvider } from "@/context/MediaLoadingContext";

export const averiaLibre = Averia_Libre({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Animesh Sharma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MediaLoadingProvider>
        <ReactLenis root>
          <body className={`${dmSans.className} antialiased`}>
            <IntroOverlay />
            <div
              className="fixed top-0 left-0 z-[999] h-screen w-screen"
              style={{
                backgroundImage: "url('/grainy-effect.webp')",
                mixBlendMode: "hard-light",
                opacity: 0.06,
                pointerEvents: "none",
              }}
            ></div>
            <div className="relative z-[99]">
              <Header />
              {children}
            </div>
            <div className="-z-10 h-screen"></div>
            <Footer />
          </body>
        </ReactLenis>
      </MediaLoadingProvider>
    </html>
  );
}
